name: Build Fritzing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev libpng-dev libjpeg-dev libxml2-dev libxslt1-dev libsqlite3-dev

    - name: Build Fritzing
      run: |
        mkdir build
        cd build
        qmake ../fritzing-app
        make

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Install dependencies
      run: |
        choco install -y cmake
        choco install -y git
        choco install -y python

    - name: Build Fritzing
      run: |
        mkdir build
        cd build
        qmake ../fritzing-app
        nmake

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'

    - name: Install dependencies
      run: |
        brew update
        brew install cmake
        brew install libpng
        brew install libjpeg
        brew install libxml2
        brew install libxslt
        brew install sqlite

    - name: Build Fritzing
      run: |
        mkdir build
        cd build
        qmake ../fritzing-app
        make
